[theme]
base = "dark"
primaryColor = "#58a6ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#fafafa"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[browser]
gatherUsageStats = false

[server]
headless = true
